import Head from "next/head";
interface props {
  page: string;
}
const HeadCustom: React.FC<props> = ({ page }) => {
  return (
    <Head>
      <title>{`Razzi | ${page}`}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="./favicon-razzi.png" />
    </Head>
  );
};

export default HeadCustom;
